#!/usr/bin/env python3
"""PIV PreCompact session snapshot.

Bundled with the cc plugin (hooks/hooks.json). Before Claude Code compacts the
conversation (manual `/compact` or automatic), this writes a coarse, disk-derived
session cursor in the same six-section format `/cc:pause` uses — so if the
compaction loses "where were we?" context, the next `/cc:prime --resume` still
has an anchor. It is deliberately dumber than a real `/cc:pause`: it can only
see the filesystem, never the conversation.

The "where are we?" logic lives in `piv_state.py` (same dir) — the single source
of truth shared with `piv-status.py`, so the three can never drift.

Design rules (this runs on EVERY compaction in EVERY project of EVERY cc installer):
  * Gentle — write NOTHING unless the cwd is actually using PIV (a `.specify/`
    dir exists). Non-PIV projects are untouched.
  * Never clobber — a human-authored `[WORKSPACE_DIR]/session.md` (from a real
    `/cc:pause`) is NEVER overwritten. If `session.md` exists — for any reason —
    we write to `session.auto.md` instead. Only `session.auto.md` (ours) is
    ever overwritten.
  * Unbreakable — wrapped in try/except; ALWAYS exit 0. A snapshot helper must
    never break a session or block a compaction.
  * Zero dependencies — standard library only, no network, fast.
"""

from __future__ import annotations

import datetime
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from piv_state import (  # noqa: E402  (local module, path set above)
    REVIEW_IGNORE,
    WORKSPACE_DIR,
    _artifact_times,
    _newest,
    detect_state,
)

AUTO_MARKER = "<!-- auto-generated by PreCompact hook, not /cc:pause -->"
AUTO_FILENAME = "session.auto.md"
MAX_LISTED_PATHS = 15  # cap the per-file list; it's a cursor, not a diff


def _git_raw(cwd: Path, *args: str) -> str:
    """Git stdout, UNstripped — porcelain lines start with a significant space."""
    try:
        out = subprocess.run(
            ["git", *args], cwd=cwd, capture_output=True, text=True, timeout=3
        )
        return out.stdout if out.returncode == 0 else ""
    except Exception:
        return ""


def _git(cwd: Path, *args: str) -> str:
    return _git_raw(cwd, *args).strip()


def _status_summary(cwd: Path) -> tuple[str, list[str]]:
    """Counted summary of `git status --porcelain` + a capped path list.

    Returns ("<N> modified, <N> added, <N> deleted, <N> untracked", [paths]).
    Counts, not a pasted diff — same rule as /cc:pause step 2.
    """
    modified = added = deleted = untracked = 0
    paths: list[str] = []
    for line in _git_raw(cwd, "status", "--porcelain").splitlines():
        if len(line) < 4:
            continue
        xy, path = line[:2], line[3:].strip()
        if xy == "??":
            untracked += 1
        elif "D" in xy:
            deleted += 1
        elif "A" in xy:
            added += 1
        else:  # M, R, C, U and friends — "changed" is close enough for a cursor
            modified += 1
        paths.append(path)
    summary = (
        f"{modified} modified, {added} added, {deleted} deleted, "
        f"{untracked} untracked"
    )
    return summary, paths


def _links(cwd: Path, workspace: Path) -> list[str]:
    """Newest artifact per evidence dir, as `## Links` bullet lines.

    Ranked by git commit time like detect_state, so "Links" and "Stopped at"
    can't name different "newest" artifacts in the same snapshot.
    """
    times = _artifact_times(cwd)
    lines: list[str] = []
    for label, subdir, ignore in (
        ("Plan", "plans", None),
        ("Review", "code-reviews", REVIEW_IGNORE),
        ("Report", "execution-reports", None),
    ):
        newest = _newest(workspace / subdir, ignore=ignore, cwd=cwd, times=times)
        if newest is not None:
            lines.append(f"- {label}: `{WORKSPACE_DIR}/{subdir}/{newest.name}`")
    return lines or ["- (no plans, reviews, or reports yet)"]


def _build_snapshot(cwd: Path, workspace: Path) -> str:
    branch = (
        _git(cwd, "branch", "--show-current")
        or _git(cwd, "rev-parse", "--abbrev-ref", "HEAD")
        or "—"
    )
    _phase, last, nxt = detect_state(cwd)
    nxt = nxt or "/cc:next"
    counts, paths = _status_summary(cwd)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        AUTO_MARKER,
        "# Session Cursor",
        f"**Paused:** {now} · **Branch:** {branch}",
        "",
        "## Stopped at",
        f"{last} — auto-detected from disk artifacts (no `file:line`; "
        "the hook cannot see the conversation)",
        "",
        "## In flight (uncommitted)",
        counts,
    ]
    if paths:
        lines += [f"- {p}" for p in paths[:MAX_LISTED_PATHS]]
        if len(paths) > MAX_LISTED_PATHS:
            lines.append(f"- … and {len(paths) - MAX_LISTED_PATHS} more")
    else:
        lines.append("- (working tree clean)")
    lines += [
        "",
        "## Open threads",
        "- Auto-snapshot written before context compaction — NOT a substitute "
        "for a real `/cc:pause`; conversation-level threads were not captured.",
        "",
        "## Next action",
        nxt,
        "",
        "## Links",
        *_links(cwd, workspace),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    cwd = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
    workspace = cwd / WORKSPACE_DIR

    # Gentle gate: only act in projects that actually use PIV.
    if not workspace.is_dir():
        return 0

    # Non-clobber rule: a pre-existing session.md — whatever its content — is
    # treated as human-authored and never touched. We take session.auto.md.
    target = workspace / "session.md"
    if target.exists():
        target = workspace / AUTO_FILENAME

    try:
        target.write_text(_build_snapshot(cwd, workspace), encoding="utf-8")
    except Exception:
        pass  # can't write (read-only fs, perms, …) — never block compaction
    return 0


def _self_test() -> int:
    """Embedded fixtures through the real entry point (`main()`)."""
    import tempfile

    failures = 0

    # Fixture 1: non-PIV project (no .specify/) -> writes nothing, exit 0.
    with tempfile.TemporaryDirectory() as tmp:
        os.environ["CLAUDE_PROJECT_DIR"] = tmp
        rc = main()
        leftovers = list(Path(tmp).rglob("*"))
        ok = rc == 0 and leftovers == []
        print(f"{'PASS' if ok else 'FAIL'}  non-PIV dir writes nothing, exit 0")
        failures += 0 if ok else 1

    # Fixture 2: PIV dir, no session.md -> writes session.md with marker, exit 0.
    with tempfile.TemporaryDirectory() as tmp:
        workspace = Path(tmp) / WORKSPACE_DIR
        (workspace / "plans").mkdir(parents=True)
        (workspace / "plans" / "some-feature.md").write_text("# plan\n")
        os.environ["CLAUDE_PROJECT_DIR"] = tmp
        rc = main()
        cursor = workspace / "session.md"
        content = cursor.read_text(encoding="utf-8") if cursor.is_file() else ""
        ok = (
            rc == 0
            and content.startswith(AUTO_MARKER)
            and "# Session Cursor" in content
            and "## Stopped at" in content
            and "## In flight (uncommitted)" in content
            and "## Open threads" in content
            and "## Next action" in content
            and "## Links" in content
            and not (workspace / AUTO_FILENAME).exists()
        )
        print(f"{'PASS' if ok else 'FAIL'}  PIV dir without session.md gets "
              f"marked session.md, exit 0")
        failures += 0 if ok else 1

    # Fixture 3: existing session.md is byte-for-byte untouched; the snapshot
    # goes to session.auto.md instead.
    with tempfile.TemporaryDirectory() as tmp:
        workspace = Path(tmp) / WORKSPACE_DIR
        workspace.mkdir(parents=True)
        human = workspace / "session.md"
        sentinel = b"# Session Cursor\nhuman-authored sentinel \xf0\x9f\x93\x8c\n"
        human.write_bytes(sentinel)
        os.environ["CLAUDE_PROJECT_DIR"] = tmp
        rc = main()
        auto = workspace / AUTO_FILENAME
        auto_text = auto.read_text(encoding="utf-8") if auto.is_file() else ""
        ok = (
            rc == 0
            and human.read_bytes() == sentinel
            and auto_text.startswith(AUTO_MARKER)
        )
        print(f"{'PASS' if ok else 'FAIL'}  existing session.md untouched, "
              f"snapshot lands in {AUTO_FILENAME}")
        failures += 0 if ok else 1

    # Fixture 4: in a real git repo, counted status lands in the snapshot with
    # intact paths (guards the porcelain leading-space parsing). Skips cleanly
    # if git is unusable in the test environment.
    with tempfile.TemporaryDirectory() as tmp:
        cwd = Path(tmp)
        git_ok = True
        try:
            for args in (
                ["init", "-q"],
                ["config", "user.email", "t@t"],
                ["config", "user.name", "t"],
            ):
                subprocess.run(["git", *args], cwd=cwd, capture_output=True,
                               timeout=5, check=True)
            (cwd / "tracked.txt").write_text("hi\n")
            subprocess.run(["git", "add", "-A"], cwd=cwd, capture_output=True,
                           timeout=5, check=True)
            subprocess.run(["git", "commit", "-qm", "init"], cwd=cwd,
                           capture_output=True, timeout=5, check=True)
            (cwd / "tracked.txt").write_text("hi\nchanged\n")
        except Exception:
            git_ok = False
        if git_ok:
            (cwd / WORKSPACE_DIR).mkdir()
            os.environ["CLAUDE_PROJECT_DIR"] = tmp
            rc = main()
            content = (cwd / WORKSPACE_DIR / "session.md").read_text(
                encoding="utf-8")
            ok = rc == 0 and "1 modified" in content and "- tracked.txt" in content
            print(f"{'PASS' if ok else 'FAIL'}  git status counts and paths "
                  f"parse intact in a real repo")
            failures += 0 if ok else 1
        else:
            print("PASS  git repo fixture skipped (git unusable here)")

    os.environ.pop("CLAUDE_PROJECT_DIR", None)
    print(f"self-test: {4 - failures}/4 passed")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        sys.exit(_self_test())
    try:
        sys.exit(main())
    except Exception:
        # Never let a snapshot helper break a session or block compaction.
        sys.exit(0)
